### ISSUE TITLE
Cannot run Pantheon

### ISSUE THREAD

**Issue by yuntiantian** [StanfordSNR/pantheon#57]
When I test schemes in emulated networks locally by run:
src/experiments/test.py local --all 

It reported the following error:
$ /home/wjh/PantheonRoot/pantheon/src/experiments/git_summary.sh
Testing scheme fillp_sheep for experiment run 1/1...
$ /home/wjh/PantheonRoot/pantheon/src/wrappers/fillp_sheep.py run_first
[tunnel server manager (tsm)] $ python /home/wjh/PantheonRoot/pantheon/src/experiments/tunnel_manager.py
tunnel manager is running
[tunnel client manager (tcm)] $ mm-link /home/wjh/PantheonRoot/pantheon/src/experiments/12mbps.trace /home/wjh/PantheonRoot/pantheon/src/experiments/12mbps.trace --uplink-log=/home/wjh/PantheonRoot/pantheon/src/experiments/data/fillp_sheep_mm_datalink_run1.log --downlink-log=/home/wjh/PantheonRoot/pantheon/src/experiments/data/fillp_sheep_mm_acklink_run1.log python /home/wjh/PantheonRoot/pantheon/src/experiments/tunnel_manager.py
prompt [tsm]
kill_proc_group: killed process group with pgid 434
Traceback (most recent call last):
  File "src/experiments/test.py", line 808, in main
    run_tests(args)
  File "src/experiments/test.py", line 782, in run_tests
    Test(args, run_id, cc).run()
  File "src/experiments/test.py", line 735, in run
    if not self.run_congestion_control():
  File "src/experiments/test.py", line 686, in run_congestion_control
    return self.run_with_tunnel()
  File "src/experiments/test.py", line 533, in run_with_tunnel
    ts_manager, tc_manager = self.run_tunnel_managers()
  File "src/experiments/test.py", line 297, in run_tunnel_managers
    preexec_fn=os.setsid)
  File "/home/wjh/PantheonRoot/pantheon/src/helpers/subprocess_wrappers.py", line 34, in Popen
    return subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
tunnel_manager: caught signal 15 and cleaned up
Is some dependency not installed or the setup error?

**Comment by samar1tan** [comment]
Based on my own experience, I guess that there exists some unsatisfied dependencies. You can step into the specific *.py (in your case `/home/wjh/PantheonRoot/pantheon/src/helpers/subprocess_wrappers.py, line 34, in Popen`) to look for what exactly `Popen` tried to open but failed, which might be the missing dependency.

**Comment by francisyyan** [comment]
Exactly -- for an error such as "No such file or directory," you would want to double check if you have followed the instructions in README; in particular, the "Preparation," "Dependencies," and "Setup" sections. In general, if the backtrace indicates that scheme X fails, you can always try manually running the scheme X (as shown in the "Running a single congestion control scheme" section).

Please post to our Google group or send an email to pantheon-stanford@googlegroups.com if you have any other questions. Thanks!

**Comment by yuntiantian** [comment]
What is your email address? I want to ask you some questions about Pantheon in private.

**Comment by Allen-kevin** [comment]
Hi ,i have the same problem, when I test schemes in emulated networks locally by run:
src/experiments/test.py local --all
$ /users/kai/pantheon/src/experiments/git_summary.sh
Testing scheme fillp_sheep for experiment run 1/1...
$ /users/kai/pantheon/src/wrappers/fillp_sheep.py run_first
[tunnel server manager (tsm)] $ python /users/kai/pantheon/src/experiments/tunnel_manager.py
tunnel manager is running
prompt [tsm]
/users/kai/pantheon/src/experiments/12mbps.trace --uplink-log=/users/kai/pantheon/src/experiments/data/fillp_sheep_mm_datalink_run1.log --downlink-log=/users/kai/pantheon/src/experiments/data/fillp_sheep_mm_acklink_run1.log python /users/kai/pantheon/src/experiments/tunnel_manager.py
kill_proc_group: killed process group with pgid 62456
tunnel_manager: caught signal 15 and cleaned up

Traceback (most recent call last):
File "src/experiments/test.py", line 808, in main
run_tests(args)
File "src/experiments/test.py", line 782, in run_tests
Test(args, run_id, cc).run()
File "src/experiments/test.py", line 735, in run
if not self.run_congestion_control():
File "src/experiments/test.py", line 686, in run_congestion_control
return self.run_with_tunnel()
File "src/experiments/test.py", line 533, in run_with_tunnel
ts_manager, tc_manager = self.run_tunnel_managers()
File "src/experiments/test.py", line 297, in run_tunnel_managers
preexec_fn=os.setsid)
File "/users/kai/pantheon/src/helpers/subprocess_wrappers.py", line 34, in Popen
return subprocess.Popen(cmd, **kwargs)
File "/usr/lib/python2.7/subprocess.py", line 711, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
Error in tests!

I have followed the instructions in README,  and not find any error until i run src/experiments/test.py local --all
