### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by volcano1995** [StanfordSNR/pantheon#60]
When I run _src/experiments/setup.py --setup --all_ , some errors occur:
error1: $ /home/volcano/pantheon/src/wrappers/bbr.py setup_after_reboot
$ sudo modprobe tcp_bbr
modprobe: FATAL: Module tcp_bbr not found in directory /lib/modules/4.8.0-36-generic
tcp_bbr kernel module is not available
Warning: "bbr.py setup_after_reboot" failed but continuing

error2:certutil: function failed: SEC_ERROR_LEGACY_DATABASE: The certificate/key database is in an old, unsupported format.
Traceback (most recent call last):
  File "/home/volcano/pantheon/src/wrappers/quic.py", line 123, in <module>
    main()
  File "/home/volcano/pantheon/src/wrappers/quic.py", line 98, in main
    setup_quic(cc_repo, cert_dir, html_dir)
  File "/home/volcano/pantheon/src/wrappers/quic.py", line 70, in setup_quic
    check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'certutil -d /home/volcano/.pki/nssdb -N -f /home/volcano/pantheon/src/wrappers/quic-certs/cert_pwd' returned non-zero exit status 255
Traceback (most recent call last):
  File "src/experiments/setup.py", line 59, in <module>
    main()
  File "src/experiments/setup.py", line 55, in main
    setup(args)
  File "src/experiments/setup.py", line 45, in setup
    check_call([cc_src, 'setup'])
  File "/home/volcano/pantheon/src/helpers/subprocess_wrappers.py", line 24, in check_call
    return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/volcano/pantheon/src/wrappers/quic.py', 'setup']' returned non-zero exit status 1

Anyone has ideas? Thanks a lot!!!

**Comment by jestjest** [comment]
For the first error, have you checked whether the `tcp_bbr` module exists in that directory? If so, maybe run `depmod -ae`. If not, you need that module installed first (what kernel version are you running?)

And for the second error, I believe you have already posted [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pantheon-stanford/XhO4B9_CTJY/eY_FHBPjBQAJ).

That being said, it would be good to describe what you have done already to debug this.

**Comment by volcano1995** [comment]
> For the first error, have you checked whether the `tcp_bbr` module exists in that directory? If so, maybe run `depmod -ae`. If not, you need that module installed first (what kernel version are you running?)
> 
> And for the second error, I believe you have already posted [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pantheon-stanford/XhO4B9_CTJY/eY_FHBPjBQAJ).
> 
> That being said, it would be good to describe what you have done already to debug this.

Thanks a lot!!! For the first error, I install tcp_bbr with the guide _https://www.jwtechtips.top/install-tcp-bbr-on-linux-in-1-step/_, and it works.
For the second error, I run _sudo certutil -L -d sql:/home/volcano/.pki/nssdb_ first, then run  _src/experiments/setup.py --setup --all_ with **sudo**, the error disappeared.

**Comment by francisyyan** [comment]
Thank you for your questions! Could you please send these questions to our Google group instead (unless they are real issues)?
