### ISSUE TITLE
95th one way delay is negtive??

### ISSUE THREAD

**Issue by wen-zheng** [StanfordSNR/pantheon#71]
I test pantheon in my vm,  one vm as client and another as server, and the algorithm is cubic, but I found that the report pdf shows negtive one way delay. Is this a bug??

**Comment by wen-zheng** [comment]
> I test pantheon in my vm, one vm as client and another as server, and the algorithm is cubic, but I found that the report pdf shows negtive one way delay. Is this a bug??
![Annotation 2020-03-19 174255](https://user-images.githubusercontent.com/33896328/77053300-1eab1580-6a09-11ea-8faa-45835ae9a9d4.png)

**Comment by francisyyan** [comment]
Good question! It's not a bug -- our one-way delay measurement relies on NTP to synchronize clocks on the two ends, and would be inaccurate (e.g., negative) if clock synchronization is not performed well. I would suggest checking whether you have synchronized clocks on the two VMs, or consider "relative" one-way delay (i.e., queuing delay if the correct minimum delay is subtracted) if applicable.

**Comment by wen-zheng** [comment]
Thanks!!
