### ISSUE TITLE
gigabit bandwidth emulation issue

### ISSUE THREAD

**Issue by LyraWang** [StanfordSNR/pantheon#72]
hello, I  used pantheon and mahimahi to emulate a gigabit bandwidth environment, and I tested qiuc(mvfst-rl) in this environment, but problem encountered. I wonder if any one has tested gigabit bandwidth in pantheon before?

my test:
1.Since there no 1000mbps.trace,  I made one myself;
2.I tested it with mahimahi command parameters:  --uplink-trace {traces_dir}/1000mbps.trace
        --downlink-trace {traces_dir}/1000mbps.trace
        --prepend-mm-cmds "mm-delay 40"
        --extra-mm-link-args "--uplink-queue=droptail --uplink-queue-args=bytes=10000000 --downlink-queue=droptail --downlink-queue-args=bytes=10000000
3.I used above parameters testing mvfst-rl.
4.The congestion control model may  not work well in this environment, so I fixed cwndbytes to 10000000 bytes(10000000 = 1000mbps *( 40ms * 2) / (8bits/bytes)).

To a 1000mbps bandwidth with minrtt=80ms(40*2), cwndbytes=10000000 should be the ideal value,  but I found it not work well.   high delay and high packet loss happened, the egress throughput  violently jump between 1MBps-193Mbps.
 
I reduced the bandwidth to 500mbps and remain mm-delay=40ms, and I fixed cwndbytes to 5000000 , the abnormal phenomenon disappeared.

I also tested :
800mbps, the abnormal phenomenon exist.
650mbps,  the abnormal phenomenon also exist, but not as severe as 800mbps or 1000mbps, the delay and loss rate are lower

So I am confused if pantheon and mahimahi can work well with large bandwidth?
I will be grateful for anyone who sharing any experience about testing large bandwidth in pantheon.

**Comment by francisyyan** [comment]
Thanks for the question. Mahimahi is accurate up to about 200 Mbps since it was designed to emulate commercial cellular networks. Please check out Keith's full [answer](https://groups.google.com/d/msgid/pantheon-stanford/d8a4a739-fd9f-4ddc-9877-570401f19502%40googlegroups.com) in our [Google group](https://groups.google.com/forum/#!forum/pantheon-stanford).
