### ISSUE TITLE
Does pantheon's remote mode support for Quic ?

### ISSUE THREAD

**Issue by z6833** [StanfordSNR/pantheon#73]
Hello.
Pantheon tests can be run locally over `mahimahi` using `Quic` transporting protocol based on UDP. Now I am trying to run Pantheon tests using its `remote` mode . I want to know whether I can appoint the transporting protocol `Quic` between  two remote machines with pantheon running . In other words, does pantheon's remote mode support for `Quic` protocol ? which protocol does it use while running tests over the real Internet environments to a remote machine ?
Looking forward to you reply . Thanks so much .

**Comment by z6833** [comment]
Whether `MahiMahi` can be replaced by`Mininet` while running local mode or not ?

**Comment by keithw** [comment]
Pantheon supports the same collection of schemes in both modes. QUIC is one of the supported schemes, but please note that Pantheon is importing the QUIC implementation from Google's "proto-quic" repository, which Google abandoned in 2017. Google seems to be working on a much newer QUIC library now (which they call QUICHE), but it isn't done yet.

Mahimahi and Mininet do different things -- Mahimahi's tools emulate various effects along the network path (loss, delay, varying link capacity and patterns of packet delivery). Mininet doesn't do any of that. There are in-kernel tools like netem that do some of these things. You can probably somehow configure Pantheon to use netem but we haven't done this.
