### ISSUE TITLE
About emulation trace

### ISSUE THREAD

**Issue by wen-zheng** [StanfordSNR/pantheon#74]
Hi, are all traces constant like 12Mbps in [https://github.com/StanfordSNR/pantheon/tree/master/tests](https://github.com/StanfordSNR/pantheon/tree/master/tests), I can't find out the traces of 60mpbs, 108mbps in this folder. where should I access them or how to create them?

![374792fae96a7c6e4d11acfcf05a09b](https://user-images.githubusercontent.com/33896328/79840656-c6d94300-83e8-11ea-8b8f-a8df1ebee985.png)
![5cfac49a948fc5fefed035e0d9f8f5d](https://user-images.githubusercontent.com/33896328/79840663-c9d43380-83e8-11ea-8b50-1b5ac55861e3.png)

**Comment by keithw** [comment]
https://github.com/StanfordSNR/pantheon-traces

**Comment by wen-zheng** [comment]
thanks!

**Comment by wen-zheng** [comment]
This website can't [pantheon](Pantheonpantheon.stanford.edu) be accessed currently.

**Comment by francisyyan** [comment]
Thank you so much for letting us know! It's back online now.
