### ISSUE TITLE
command to run ccs with varying delays

### ISSUE THREAD

**Issue by huiyusun** [StanfordSNR/pantheon#75]
Hello,

I noticed that in the running options, I can vary the run-times, number of flows, etc. But is there a command for running with varying delays or link-speeds? For example, if I wanted to do 3 runs with taova on the emulator with delays of 10ms, 50ms and 150ms, how can I do that?

Best,

Huiyu

**Comment by francisyyan** [comment]
Unfortunately this feature is not supported by Mahimahi, the emulator used by Pantheon.
