### ISSUE TITLE
test schemes remote

### ISSUE THREAD

**Issue by huiyusun** [StanfordSNR/pantheon#76]
Hi,

To test schemes remotely, what should the values of HOST and PANTHEON-DIR be? Is it my local host ip and my local host pantheon dir?

Best,

Huiyu

**Comment by francisyyan** [comment]
For questions about how to use the software, please check out our [Google group](https://groups.google.com/forum/#!forum/pantheon-stanford) or send an email to pantheon-stanford@googlegroups.com. Please open a GitHub issue if you find a bug in our code (or generally some sort of "issue"). Thank you!
