### ISSUE TITLE
can I reproduce this type of result using this repository?

### ISSUE THREAD

**Issue by wen-zheng** [StanfordSNR/pantheon#78]
I want to plot this type of figure:
![Annotation 2020-05-17 002237](https://user-images.githubusercontent.com/33896328/82124872-8f399d00-97d4-11ea-88b2-6ff36167648b.jpg)
I mean the shaded region like the above.  Can I reproduce this type of result using this repository's scripts?

**Comment by francisyyan** [comment]
Please check out https://github.com/StanfordSNR/pantheon/blob/scripts-for-paper/analysis/plot_json.py and https://github.com/StanfordSNR/pantheon/blob/scripts-for-paper/analysis/analyze_helpers.py#L37.

**Comment by wen-zheng** [comment]
Thanks
