### ISSUE TITLE
Does remote mode support for traffic controling ?

### ISSUE THREAD

**Issue by z6833** [StanfordSNR/pantheon#79]
Hi, I want to train a model (remote mode) by using a dynamic changing envs of net . Is there any interfaces or parms in pantheon that I can use to achieve it ? For example,  changing sending rate of packets or changing intervals among packets . I noticed a parms `--interval` , but it seems not work .

**Comment by francisyyan** [comment]
Hi there -- Pantheon uses [Mahimahi](http://mahimahi.mit.edu/) as the network emulator, so if you provide the desired Mahimahi trace as `--uplink-trace`/`--downlink-trace` for `src/experiments/test.py`, then `test.py` will forward the trace to Mahimahi's `mm-link` command.

As for how to generate a Mahimahi trace with varying bandwidth, please check out the manual page of `mm-link` (by running `man mm-link`). Please feel free to send a follow-up question in our [Google group](https://groups.google.com/forum/#!forum/puffer-stanford)! (Please open an issue if this's a bug in our code.) Thanks!
