### ISSUE TITLE
Questions about Pantheon's remote mode

### ISSUE THREAD

**Issue by z6833** [StanfordSNR/pantheon#80]
Hi,
I tried Remote Mode with two machines in real network with pantheon installed  and  I noticed something interesting . I am looking for your advice on follow questions .
1. Throughput is always far less than Real bandwidth . I use 1G bandwidth for testing, and the throughput always rises up to approximately 23M ， and then it begins occupying the memory , increasing delay . 
2.  Relationship between Remote Mode and mm-tunnel*. I thought mm-tunnel and mahimahi only used in local mode , but I found that mm-tunnelserver and mm-tunnelclient was used when running `test.py` . Does tunnel be used for sending data instead of real link ? What is mm-tunnel ? What's the  relationship between tunnel and remote mode ?

Looking forward to your reply .
Thanks .

**Comment by francisyyan** [comment]
Sorry for the delay -- A similar question has been asked in our [Google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/pantheon-stanford/ejXkiz6P8EE), and we'll follow up there.
