### ISSUE TITLE
How can I run Pantheon in parallel?

### ISSUE THREAD

**Issue by JerryLX** [StanfordSNR/pantheon#81]
I tried to run Pantheon in parallel (more specifically, run multiple pairs of indigo/senders and indigo/receiver) on one server, but part of the receivers seem unable to receive packets when the receivers are assigned with the same IP address.
After adding a lock on the receiver creation, It works well at the beginning. But after several runs, I got "dnsmasq: did not start after 20 attempts".
Is there any simple ways to run Patheon in parallel, cause using one Patheon environment for training is inefficient.

**Comment by francisyyan** [comment]
Thanks for your question! I assume you are asking about parallel training in simulation/emulation. Both Pantheon and Indigo use Mahimahi as the emulator, so parallel training can be achieved by instantiating multiple Mahimahi containers. For instance, if you run `mm-link` in two different terminals, you will see that two pairs of IP addresses created: `100.64.0.1<->100.64.0.2` and `100.64.0.3<->100.64.0.4`, and you can then provide different destination IP addresses for the senders so they connect to different receivers. More information can be found on Mahimahi's website or its man page.

Another thing to note is that depending on the number of cores your machine has, multiple Mahimahi links running concurrently may not be capable of achieving their desired bandwidth. E.g., emulating two 100 Mbps links at the same time could give you two links each < 100 Mbps. In that case, you can consider switching to distributed training (as we did for training Indigo), with each VM emulating one Mahimahi link and running a single pair of sender and receiver.
