### ISSUE TITLE
Running Pantheon on Android

### ISSUE THREAD

**Issue by hoax-killer** [StanfordSNR/pantheon#83]
Hi,

I want to run Pantheon client (i.e. a receiver) inside an Android native-app. The client will be the receiver while the server will be setup on a Ubuntu-based machine. Any thoughts on how to quickly setup such an environment?
If its easy, we can assume the Android phone is rooted.

Thanks,
Arvind

**Comment by francisyyan** [comment]
Hello Arvind,

Thank you for the question. If you don't mind, I am going to close this "issue" and redirect you to a similar question in our Google group: https://groups.google.com/d/msgid/pantheon-stanford/CAAMaOAMhAGe6wkr%3DY4DvKThbPJQsypoHDx7xOwihb3_8CkZGKg%40mail.gmail.com?utm_medium=email&utm_source=footer

Best,
Francis
