### ISSUE TITLE
A question about figure generation

### ISSUE THREAD

**Issue by themistbeforedawn** [StanfordSNR/pantheon#86]
Hi,

We are currently testing our congestion control algorithm using Pantheon, and we want to create figures similar to the following examples in your paper:

![image](https://github.com/StanfordSNR/pantheon/assets/110363719/94869f60-5371-415d-b53f-5d8f5192b5eb)

![image](https://github.com/StanfordSNR/pantheon/assets/110363719/976dc41e-a4ab-4b7a-a50c-e50db5447066)

Could you please provide more detailed instructions on how to generate these figures or share any open-source code that could be useful for this purpose?

Thank you very much for your help!

**Comment by francisyyan** [comment]
Thanks for your question! We used or adapted [plot_json.py](https://github.com/StanfordSNR/pantheon/blob/scripts-for-paper/analysis/plot_json.py) to plot these figures, but I suppose you are asking more about the error ellipses. They are generated using [this function](https://github.com/StanfordSNR/pantheon/blob/scripts-for-paper/analysis/analyze_helpers.py#L37).

**Comment by mistbd00** [comment]
Thanks a lot!!!!
